"""decision_quality_key_stats_evidence

Revision ID: 23317f57050f
Revises: a1b2c3d4e5f6
Create Date: 2026-09-02 14:10:54.027811
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '23317f57050f'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_key_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('str_value', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('as_of', sa.Date(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'metric_name', name='uq_key_stats_company_metric')
    )
    with op.batch_alter_table('company_key_stats', schema=None) as batch_op:
        batch_op.create_index('ix_key_stats_company', ['company_id'], unique=False)

    op.create_table('company_profiles',
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.Column('dividend_rate', sa.Float(), nullable=True),
    sa.Column('next_earnings_date', sa.String(length=32), nullable=True),
    sa.Column('quarterly_json', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('research_evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=True),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.Column('topic', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(length=128), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('published_at', sa.String(length=32), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_evidence', schema=None) as batch_op:
        batch_op.create_index('ix_evidence_company', ['company_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_evidence', schema=None) as batch_op:
        batch_op.drop_index('ix_evidence_company')

    op.drop_table('research_evidence')
    op.drop_table('company_profiles')
    with op.batch_alter_table('company_key_stats', schema=None) as batch_op:
        batch_op.drop_index('ix_key_stats_company')

    op.drop_table('company_key_stats')
    # ### end Alembic commands ###
