"""Phase 1 initial schema

Revision ID: ccf1cb226400
Revises: 
Create Date: 2026-09-01 21:43:07.841056
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'ccf1cb226400'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=True),
    sa.Column('exchange', sa.String(length=16), nullable=True),
    sa.Column('country', sa.String(length=4), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('gics_sector', sa.String(length=64), nullable=True),
    sa.Column('gics_industry', sa.String(length=128), nullable=True),
    sa.Column('custom_industry_sheet', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('indexes', sa.JSON(), nullable=True),
    sa.Column('in_sp500', sa.Boolean(), nullable=False),
    sa.Column('in_tsx_composite', sa.Boolean(), nullable=False),
    sa.Column('fiscal_year_end', sa.String(length=32), nullable=True),
    sa.Column('extraction_status', sa.String(length=32), nullable=True),
    sa.Column('source_primary', sa.String(length=64), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('company_id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_currency'), ['currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_custom_industry_sheet'), ['custom_industry_sheet'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_gics_sector'), ['gics_sector'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_ticker'), ['ticker'], unique=False)

    op.create_table('import_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_filename', sa.String(length=256), nullable=True),
    sa.Column('source_mtime', sa.Float(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.Column('companies_imported', sa.Integer(), nullable=True),
    sa.Column('fixture', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_quality_flags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_quality_flags', schema=None) as batch_op:
        batch_op.create_index('ix_flags_company', ['company_id'], unique=False)

    op.create_table('financial_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('period_type', sa.String(length=8), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=256), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('net_income', sa.Float(), nullable=True),
    sa.Column('diluted_eps', sa.Float(), nullable=True),
    sa.Column('gross_profit', sa.Float(), nullable=True),
    sa.Column('operating_cash_flow', sa.Float(), nullable=True),
    sa.Column('capex', sa.Float(), nullable=True),
    sa.Column('fcf_reported', sa.Float(), nullable=True),
    sa.Column('free_cash_flow', sa.Float(), nullable=True),
    sa.Column('fcf_calc', sa.Float(), nullable=True),
    sa.Column('netdebt_calc', sa.Float(), nullable=True),
    sa.Column('total_debt', sa.Float(), nullable=True),
    sa.Column('book_equity', sa.Float(), nullable=True),
    sa.Column('cash_st_investments', sa.Float(), nullable=True),
    sa.Column('total_assets', sa.Float(), nullable=True),
    sa.Column('total_liabilities', sa.Float(), nullable=True),
    sa.Column('ebit', sa.Float(), nullable=True),
    sa.Column('ebitda', sa.Float(), nullable=True),
    sa.Column('interest_expense', sa.Float(), nullable=True),
    sa.Column('topline_alt', sa.Float(), nullable=True),
    sa.Column('fcfmargin_calc', sa.Float(), nullable=True),
    sa.Column('grossmargin_calc', sa.Float(), nullable=True),
    sa.Column('roe_calc', sa.Float(), nullable=True),
    sa.Column('roa_calc', sa.Float(), nullable=True),
    sa.Column('pe_calc', sa.Float(), nullable=True),
    sa.Column('pb_calc', sa.Float(), nullable=True),
    sa.Column('ev_calc', sa.Float(), nullable=True),
    sa.Column('ev_to_ebitda_calc', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_currency', sa.String(length=8), nullable=True),
    sa.Column('price_asof', sa.String(length=32), nullable=True),
    sa.Column('shares_snapshot', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('cet1_ratio', sa.Float(), nullable=True),
    sa.Column('cet1_approach', sa.String(length=256), nullable=True),
    sa.Column('cet1_requirement_or_target', sa.Float(), nullable=True),
    sa.Column('total_capital_ratio', sa.Float(), nullable=True),
    sa.Column('leverage_ratio', sa.Float(), nullable=True),
    sa.Column('nim_fy2025', sa.Float(), nullable=True),
    sa.Column('nim_q4_2025', sa.Float(), nullable=True),
    sa.Column('efficiency_ratio', sa.Float(), nullable=True),
    sa.Column('roaa', sa.Float(), nullable=True),
    sa.Column('extraction_status', sa.String(length=32), nullable=True),
    sa.Column('source_primary', sa.String(length=64), nullable=True),
    sa.Column('fill_ok', sa.String(length=8), nullable=True),
    sa.Column('membership_flag', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fiscal_year', 'period_type', name='uq_snapshot_company_year_period')
    )
    with op.batch_alter_table('financial_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_snapshots_company', ['company_id'], unique=False)

    op.create_table('placements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('sheet_name', sa.String(length=64), nullable=False),
    sa.Column('placement_role', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'sheet_name', 'placement_role', name='uq_placement')
    )
    with op.batch_alter_table('placements', schema=None) as batch_op:
        batch_op.create_index('ix_placements_company', ['company_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placements', schema=None) as batch_op:
        batch_op.drop_index('ix_placements_company')

    op.drop_table('placements')
    with op.batch_alter_table('financial_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshots_company')

    op.drop_table('financial_snapshots')
    with op.batch_alter_table('data_quality_flags', schema=None) as batch_op:
        batch_op.drop_index('ix_flags_company')

    op.drop_table('data_quality_flags')
    op.drop_table('import_runs')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_ticker'))
        batch_op.drop_index(batch_op.f('ix_companies_name'))
        batch_op.drop_index(batch_op.f('ix_companies_gics_sector'))
        batch_op.drop_index(batch_op.f('ix_companies_custom_industry_sheet'))
        batch_op.drop_index(batch_op.f('ix_companies_currency'))
        batch_op.drop_index(batch_op.f('ix_companies_country'))

    op.drop_table('companies')
    # ### end Alembic commands ###
